kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
    # 把 host 上所有 nvidia container 运行时工具挂进来
  - hostPath: /usr/bin/nvidia-container-runtime
    containerPath: /usr/bin/nvidia-container-runtime
  - hostPath: /usr/bin/nvidia-container-runtime-hook
    containerPath: /usr/bin/nvidia-container-runtime-hook
  - hostPath: /usr/bin/nvidia-container-toolkit
    containerPath: /usr/bin/nvidia-container-toolkit
  - hostPath: /dev/nvidiactl
    containerPath: /dev/nvidiactl
  - hostPath: /dev/nvidia-uvm
    containerPath: /dev/nvidia-uvm
  - hostPath: /dev/nvidia0
    containerPath: /dev/nvidia0

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
    runtime_type = "io.containerd.runc.v2"
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
      # 如果你的 hook 是 runtime-hook，则用下面这行
      BinaryName = "/usr/bin/nvidia-container-runtime-hook"
      # 否则改成 "/usr/bin/nvidia-container-runtime"

